### ISSUE TITLE
Beginning Readability edits  - Question: Did you get a notice from a sheriff/constable

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-MTVHousing#1]
Why is this question in here? If my answer is Yes, I go to the question What is the reason you missed your hearing?, if I answer No I go to the question What is the reason you missed your hearing? 
And the quetion what is the reason you missed your hearing, doesn't seem to flow from getting notice from the constable - why

**Comment by mikecronin7** [comment]
If they answer yes there is a section on the document that appears which then is submitted to the court to ask them to stay the execution. if they have been contacted by a sheriff/constable this is necessary so that they are not evicted from their home before the court can hear this motion. If they have not been contacted then there is no need for that section and it does not appear in the final document if they click "no". 

There is no real connection between that question and the next hence why it doesn't flow too well but that question is necessary. If you think there is a better area to put it in we can change it around
